### ISSUE TITLE
Cannot select models from other categories

### ISSUE THREAD

**Issue by swissfreek** [tbs-fpv/freedomtx#1]
**Describe the bug**
You cannot "select" models from categories other than the default category. You can long-press models, but it only gives you options of Copy, Delete, Rename, etc. not Select.

**To Reproduce**
1. Long-press roller
2. Click on Model Select
3. Tap Page to get to second category
4. Scroll to any model in that category
5. Long-press roller
6. "Select model" is not an option

**Expected behavior**
You should be able to select models from other categories (say, all quads in one, all wings in the other, etc.).

**General information**
 - FreedomTX v1.01
 - Tango2 Pro

**Comment by tbs-fpv** [comment]
Thank you for your reports. We will look into them asap.

**Comment by tbs-fpv** [comment]
fixed in 1.10
