### ISSUE TITLE
BF Lua Scripts 1.5 not working

### ISSUE THREAD

**Issue by mfulz** [tbs-fpv/freedomtx#10]
**Describe the bug**
The actual BF Lua Scripts 1.5 are not working. Error "128x96 not supported"

**To Reproduce**
1. Download latest release https://github.com/betaflight/betaflight-tx-lua-scripts/releases
2. Copy them to SD Card
3. Start the BF script under SCRIPTS->TOOLS->bf.lua

**Expected behavior**
The script should work, or at least the tbs tango bf sd script should include the latest changes to work with BF 4.2

**General information**
 - OpenTX version -> Don't know it's the tango 2 actual firmware 1.0
 - TBS Tango 2 Pro
 - Agent X

**Comment by kamik2** [comment]
update your tango II to 1.13 and also update to the "beta" sd card content.  there is a newer version of the script included.
anyway . the brand new bf lua does not work yet on the t2

**Comment by mfulz** [comment]
How to update?
TBS Agent X is just showing the 1.01 firmware, which is the installed one.

**Comment by kamik2** [comment]
click on the 3 dots in the top right corner of the agent and then "enable beta releases"

**Comment by mfulz** [comment]
Thanks
