### ISSUE TITLE
External RF module unable to use packet rates >50hz

### ISSUE THREAD

**Issue by wvarty** [tbs-fpv/freedomtx#12]
**Describe the bug**
When using the TBS external module adapter on the Tango 2, the RC data is only being transmitted from FreedomTX to the external module at 50Hz, regardless of how fast the module is requesting it.

The packet rate over the air will correctly operate at the desired RF rate, however the stick data is only ever being updated at 50hz.

See this video for a full demonstration of the problem:
https://youtu.be/d7PEyGn55DM

**To Reproduce**
1. Connect an external module capable of rate >50hz to the Tango 2 (i.e. Crossfire micro or full sized)
2. Under the model setup, select CRSF for the External RF
3. Using the LUA script, set the external RX to use 150hz mode
4. Log BB data using the RC_SMOOTHING_RATE debug mode, and observe the rate that stick inputs change at

**Expected behavior**
RC data is updated at the same rate that the packets are being sent (i.e. 150hz).

**Actual behavior**
RC data is updated at 50hz, regardless of the RF rate.

**Screenshots**
![150hz-setup](https://user-images.githubusercontent.com/59873510/95463053-a82d2f80-09bb-11eb-9234-5db8565cb821.PNG)
![bb](https://user-images.githubusercontent.com/59873510/95463473-2093f080-09bc-11eb-89c8-e93c2f0bc69e.PNG)

**General information**
 - FreedomTX version TBS-1.2.1
 - Hardware: TBS Tango 2 Pro + External Module Mod

**Comment by kamik2** [comment]
fixed on 1.23

pls update

**Comment by juliannojungle** [comment]
@kamik2 please help me to understand: does this means that the radio can talk to the module using CRSF protocol at 50Hz (or 150Hz) over S.PORT?
I'm asking because of this [commit message](https://github.com/opentx/opentx/pull/3114), that says S.PORT uses 200K baud to talk to the module using CRSF.

Are those different things? Can you please clarify that to me? I'm dev but no hardware expert. Just trying to make things work on an old radio I have with a custom opentx.

**Comment by wvarty** [comment]
@juliannojungle those are two different things. The module requests packets from the handset at whatever frequency it needs them (50hz, 150hz for Crossfire, or 250hz for Tracer). The baud rate doesn't really affect the packet update rate, and really only affects the time it takes for the handset to transmit one full packet to the module via the UART. The baud rate for the CRSF protocol is 400k (not sure where you dug up that 200k from, but it looks pretty old), which is plenty fast enough to get the packets to the module with minimal latency overhead.

@kamik2 I can confirm this has been fixed in 1.23. Closing the issue.
