### ISSUE TITLE
Support for ImmersionRC Ghost Receivers

### ISSUE THREAD

**Issue by mfulz** [tbs-fpv/freedomtx#18]
ImmersionRC Ghost Receivers are not supported by FreedomTX but by OpenTX

Can you add the Ghost stuff to FreedomTX please?

Further Question: When / will the Tango 2 Stuff be merged back upstream to OpenTX? I thought it's a temporary fork and will be merged back, but I can't see any progress or timelines for this.
I really hope that this wasn't just marketing and won't happen :(

**Comment by israelshirk** [comment]
4.0

**Comment by israelshirk** [comment]
Apologies, 2.4.  Too many projects in my head 😜

**Comment by mfulz** [comment]
As I don't know how long it'll take to the release of 2.4 for opentx are you planning to integrate the ghost receivers to freedomtx?
I just want to know approx. how long I've to wait as I got a ghost sender as present and can't use it :(

**Comment by mfulz** [comment]
Is there any info in this?
Would it be possible that I extract the needed changes from opentx and create a pull request?
I'm strugeling with finding information in how to add patches to this freedomtx

**Comment by abcleanonme** [comment]
Very excited for this sort of integration, however stream-crossing it may seem 😜. Any updates or info on this front?

**Comment by mfulz** [comment]
I've flashed my ghost now to expresslrs, which uses crsf so doesn't matter anymore ;)
