### ISSUE TITLE
Roller behavior unintuitive

### ISSUE THREAD

**Issue by swissfreek** [tbs-fpv/freedomtx#2]
**Is your feature request related to a problem? Please describe.**
The roller direction does not (in my opinion) correspond intuitively. When scrolling through a vertical menu, rolling to the left slides down the list, and right slides up the list. I think this makes sense. But when changing values (eg adjusting endpoints or changing a name), left makes the number/letter increase, and right makes it decrease. Right should increase the number, left should decrease. Most infuriatingly, on side-to-side like when editing a logical switch, rolling LEFT moves the cursor RIGHT. This makes it impossible to wrap your head around which way the cursor is going to go when you turn the roller. Up? Right? Diagonal?

**Describe the solution you'd like**
Please change the roller so that right makes numbers/letter increase and so that left is left and right is right. Ideally, we could get the option of switching whether right was up or left was up, but even if this was added, numbers still increase the opposite way from menus.

**Comment by tbs-fpv** [comment]
fixed in 1.10
