### ISSUE TITLE
Model match behavior inconsistent

### ISSUE THREAD

**Issue by swissfreek** [tbs-fpv/freedomtx#4]
**Describe the bug**
Model match only prevents binding on power-up. If you power up on the correct model, the receiver will bind and function normally. Once bound to the correct model, if you switch to a different model (that has a different RXNum), the link will remain active and function, even on the wrong model. If you then shut the radio down and power it back up (still on the wrong model), the receiver will not bind. Then, if you change to the correct model, it will still not bind. You have to shut the radio down and power it back up on the correct model for the receiver to connect properly.

**To Reproduce**
1. Bind to one model with a certain RxNum value (RX will be connected).
2. Change models in the radio to one with a different RxNum value (RX stays connected, but should not be).
3. Turn off radio and power it back on without changing models (RX will be disconnected).
4. Switch back to model with correct RxNum (RX will stay disconnected, but should be).
5. Power radio down and back on without changing models (RX will connect properly).

**Expected behavior**
Radio should check RxNum when changing models, so that if you are on the right model but switch to the wrong one, the link is broken, or if you are on the wrong model and it won't link, but then realize it and switch to the correct one, the link should establish, without needing to power cycle the radio or receiver after changing models.

**Comment by tbs-fpv** [comment]
fixed in 1.10
